import { test, expect } from "@playwright/test";

test("slash compact works by Enter and tap, keeps transcript, and logs only summary", async ({ page }) => {
  await page.goto("/");
  await page.getByRole("button", { name: /новый диалог/i }).first().click();
  await page.getByTestId("strategy-card-summary").click();
  const input = page.getByRole("textbox");
  const meter = page.getByRole("region", { name: "Статистика контекста" });
  const transcript = page.getByRole("region", { name: "Переписка" });
  expect(await meter.evaluate((element) => Boolean(element.compareDocumentPosition(document.querySelector('[aria-label="Переписка"]')) & Node.DOCUMENT_POSITION_PRECEDING))).toBe(true);
  await expect(transcript).toBeVisible();
  for (const text of ["Первое сообщение: кофе без молока", "Второе сообщение: доза 18 г"]) {
    await input.fill(text);
    const response = page.waitForResponse(r => r.url().endsWith("/messages") && r.request().method() === "POST");
    await page.getByRole("button", { name: "Отправить", exact: true }).click();
    expect((await response).ok()).toBeTruthy();
    await expect(input).toBeEnabled();
  }
  await expect(page.getByRole("progressbar")).toHaveAttribute("aria-valuenow", "150");
  await expect(page.getByRole("progressbar")).toHaveAttribute("aria-valuemax", "1000");
  const beforeScroll = await input.boundingBox();
  await transcript.evaluate(element => { element.scrollTop = 0; });
  const afterScroll = await input.boundingBox();
  expect(afterScroll.y).toBe(beforeScroll.y);
  expect(afterScroll.y + afterScroll.height).toBeLessThanOrEqual(900);
  expect(await page.evaluate(() => document.documentElement.scrollHeight <= innerHeight)).toBe(true);
  await page.getByRole("button", { name: "Копировать ID чата" }).click();
  expect(await page.evaluate(() => navigator.clipboard.readText())).toMatch(/^[a-f0-9]{32}$/);
  await input.fill("/wrong");
  await expect(page.getByRole("button", { name: /compact/ })).toHaveCount(0);
  await page.locator("form").screenshot({ path: "test-results/context-status-desktop.png", animations: "disabled" });
  await input.fill("/co");
  await expect(page.getByRole("button", { name: /compact/ })).toBeVisible();
  await page.screenshot({ path: "test-results/compact-desktop.png", fullPage: true, animations: "disabled" });
  const result = page.waitForResponse(r => r.url().endsWith("/compact"));
  await input.press("Enter");
  const response = await result;
  expect(response.ok()).toBeTruthy();
  const dialog = await response.json();
  expect(dialog.messages).toHaveLength(4);
  expect(dialog.compression.covered_messages).toBe(4);
  expect(dialog.context_strategy).toBe("summary");
  await expect(page.getByText(/^Контекст сжат:/)).toBeVisible();
  await expect(input).toHaveValue("");
  await expect(page.getByText("Первое сообщение: кофе без молока", { exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByText("Первое сообщение: кофе без молока", { exact: true })).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  const mobileInput = await input.boundingBox();
  expect(mobileInput.y + mobileInput.height).toBeLessThanOrEqual(844);
  expect(await page.evaluate(() => document.documentElement.scrollHeight <= innerHeight)).toBe(true);
  expect(await transcript.evaluate(element => element.scrollHeight > element.clientHeight)).toBe(true);
  await transcript.evaluate(element => { element.scrollTop = 0; });
  await page.locator("form").screenshot({ path: "test-results/context-status-mobile.png", animations: "disabled" });
  await input.fill("/");
  const command = page.getByRole("button", { name: /compact/ });
  await expect(command).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: "test-results/compact-mobile.png", fullPage: true, animations: "disabled" });
  const again = page.waitForResponse(r => r.url().endsWith("/compact"));
  await command.click();
  expect((await again).ok()).toBeTruthy();
  await expect(page.getByText(/Summary обновлено/)).toBeVisible();
  const logs = await (await page.request.get(`/api/admin/logs?dialog_id=${dialog.id}&action=lookup`)).json();
  const requests = logs.logs.filter(log => log.event === "llm_request");
  expect(requests.filter(log => log.purpose === "summary")).toHaveLength(2);
  expect(requests.filter(log => log.purpose === "chat")).toHaveLength(2);
  expect(JSON.stringify(requests)).not.toContain("/compact");
});
